【マッチング】モデル, テーブルl作成(Menu)
great084/creator_match_pf pull request #41
Opened 2021-02-13 04:27 UTC by fumi238000

## 実装の目的と概要
- Menuモデル作成とTBL作成

## 実装内容(技術的な点を記載)
- Menuテーブルの作成
- MenuとCreatorの関連付け
- テストデータの作成

## 重点的に見てほしいところ(不安なところ)
 - TBLの作成(Userテーブルとの関連付け）
 

## チェックリスト
- [ ] ローカル環境での動作確認をしたか（影響し得る範囲も含めて）
- [ ] rubocopを実行して警告が出力されていないか
- [ ] GitHub で ファイル差分（Files changed）を確認し、内容が合っているか。不要なファイルに差分がでていないか

## 確認法方
- 以下のコマンドで確認お願いいたします
```
# Menuテーブルの作成
rails db:migrate:reset 

# 初期データの導入
rails db:seed

# コンソール 起動
rails c

# Menuを取得できるか確認
creator = Creator.first
creator.menus 
```
## 備考
- 「TBLの作成(Userテーブルとの関連付け）」という項目は、Creatorとは別に、Userにも関連付けが必要なのでしょうか？

2021-02-13 14:33 UTC, great084 requested changes
Model, TBL設定は問題ありません。

seeds.rbについて対応お願いしたい点があります。

2021-02-13 14:33 UTC, great084 commented on db/seeds.rb
>    email: "client1@example.com",
この記載だと、データ存在する際はエラーになり、毎回dbをクリアしてからでないとテストデータが作成できないので、`find_or_create_by`を使って、存在しない場合だけcreateするようにしてほしいです。
そうすればテストデータの状態によらず、実行エラーが防げますので。

- 記述例
```
User.find_or_create_by!(email: "test@exampl.com") do |user|
  user.password = PASSWORD
  puts "ユーザのテストデータを作成しました"
end
```

（元ののuser作成のときから良くなかったですね。すみません）
お手数おかけしますが、creator,clientも含めて対応してもらえると助かります。

2021-02-13 23:07 UTC, fumi238000 commented
## 修正
- `seeds.rb`に`find_or_create_by!`を実装
- テストデータの修正

## 備考
- `seeds.rb`に`puts`を導入したのですが、rubocopに弾かれてしまいました。そのため、`rubocop:disable all`をコメントに追記して無効化しております。他の方法がありましたら教えて頂けると幸いです。

## 参考資料
- [RuboCopの警告をコメントで無効化する方法](https://qiita.com/tbpgr/items/a9000c5c6fa92a46c206)

2021-02-14 01:38 UTC, great084 approved these changes
確認しました。OKです。

> seeds.rbにputsを導入したのですが、rubocopに弾かれてしまいました。そのため、rubocop:disable allをコメントに追記して無効化しております。他の方法がありましたら教えて頂けると幸いです。

今の`rubocop:disable all`追記でも良いと思います。
また別の方法としては、rubocop設定ファイルに、seedファイルの場合のみ、標準出力チェック（Rails/Output）を無効にする設定を入れるのも一つかと思います。

2021-02-14 11:58 UTC, fumi238000 commented
> 今のrubocop:disable all追記でも良いと思います。
今回はこちらで行きたいと思います。
今後も同じような場面があれば、その時対応させて頂います！

2021-02-14 14:46 UTC, yuukii125 approved these changes

2021-02-14 15:18 UTC, merged