【マッチング】仕事の依頼, 契約条件の編集
great084/creator_match_pf pull request #52
Opened 2021-02-18 05:40 UTC by fumi238000

## 実装の目的と概要
- ①仕事の依頼ができる
- ②契約条件が変更できる
- ③契約中の仕事を表示

## 実装内容(技術的な点を記載)
① 仕事の依頼ができる
-  [ ] マイページ（仮）より、「詳細をみる」ボタンで`menu_show`へ遷移 
-  [ ] `menu_show`の「お仕事依頼ページに進む」ボタンで、createアクションへ遷移し、Taskのテーブルが作成される

②契約条件が変更できる
-  [ ] マイページ（仮）より、「詳細をみる」ボタンで`menu_show`へ遷移
-  [ ] 詳細画面から、「>>編集」で`menu_edit`へ遷移  
- [ ] 「確定する」ボタンで、更新できる

③契約中の仕事を表示できる
- [ ] マイページ（仮）`menus`より、マッチングしている仕事を閲覧できる
- [ ] 仕事に遷移することができる  

## 重点的に見てほしいところ(不安なところ)
- `Task.rb`のenumの挙動
- 契約条件の入力・保存方法（納期)
- バリデージョン部分の不足、変更

## チェックリスト
- [ ] ローカル環境での動作確認をしたか（影響し得る範囲も含めて）
- [ ] rubocopを実行して警告が出力されていないか
- [ ] GitHub で ファイル差分（Files changed）を確認し、内容が合っているか。不要なファイルに差分がでていないか

## 備考（実装していないことなど）
- ログインユーザー（クライアント、クリエイター）によって、挙動が少し異なっています。（例：クリエイターは仕事を依頼できないなど。確認中です。）
- マイページが現状仮の状態ですので、実装を早急にあげたいと思います。

2021-02-19 00:16 UTC, great084 commented
@fumi238000 
まだ全ては見切れていませんが、Menuに対してログイン状態による制御ができていないと思います。
（issueリンク貼ってあったので、実装済みかと思ったのですが・・）

具体的には、
・ログインしなくても、menuの新規作成、編集、削除ができる
・クライアントでログインしても、menuの新規作成、編集、削除ができる
・他のクリエイターが作成したmenuに対しても編集、削除ができる

2021-02-19 08:00 UTC, great084 commented
確認しました。

## サービスの動作確認について
### 未ログインユーザ
- メニューの一覧から詳細を確認しようとすると以下のエラーになる

```
ActionView::Template::Error (undefined method `id' for nil:NilClass):
    17: </div>
    18: 
    19: <%# TODO: if文でクライアントのみ表示させる%>
    20: <%= link_to tasks_path(task: { menu_id: @menu.id, creator_id: @menu.creator.id, client_id: current_user.id, name: @menu.title, contract_money: @menu.price}), 
    21:              data: { confirm: '仕事を依頼します。よろしいでしょうか？'},
    22:              method: :post do %>
    23: <button>お仕事依頼ページに進む</button>
  
app/views/menus/show.html.erb:20
```

- メニューの一覧画面で新規作成ボタンが表示される（リンク表示の制御が必要）※マイページの実装でおこなう？
- メニューの新規作成(/menu_new)にアクセスすると以下のエラーが出力されて、システムエラーとなる

```
Completed 500 Internal Server Error in 4ms (ActiveRecord: 0.0ms | Allocations: 1149)
NoMethodError (undefined method `[]' for nil:NilClass):  
app/controllers/menus_controller.rb:55:in `set_creator' 
```

### クライアント
- メニューの一覧画面で新規作成ボタンが表示される（リンク表示の制御が必要）※マイページの実装でおこなう？
- メニューの新規作成を行うとシステムエラーにはならないが、menus#create 内に
- メニュー詳細画面は表示できるが、編集、削除ボタンが表示される（リンク表示の制御が必要）※マイページの実装でおこなう？
-

2021-02-20 04:19 UTC, fumi238000 commented
https://github.com/great084/creator_match_pf/pull/52#issuecomment-781904603
## 修正点への対応
### ①未ログインユーザ
- エラーは、`current_user`が絡む部分で発生しています。
そのため、未ログインユーザーの場合は、current_userが絡む部分を非表示にすることで対応します。
>メニューの一覧から詳細を確認しようとすると以下のエラーになる
ログインしていない場合は、マッチングボタンを非表示にすることで、エラーから回避します。

> メニューの一覧画面で新規作成ボタンが表示される（リンク表示の制御が必要）※マイページの実装でおこなう？

*マイページの実装で非表示にします。*

> メニューの新規作成(/menu_new)にアクセスすると以下のエラーが出力されて、システムエラーとなる

*ログインしていない場合は新規作成ボタンを非表示に設定することで、エラーを回避します*


### ②クライアント
> メニューの一覧画面で新規作成ボタンが表示される（リンク表示の制御が必要）※マイページの実装でおこなう？
> メニューの新規作成を行うとシステムエラーにはならないが、menus#create 内に
> メニュー詳細画面は表示できるが、編集、削除ボタンが表示される（リンク表示の制御が必要）※マイページの実装でおこなう？

*マイページの実装で非表示にしてもらい、メニューの新規作成、編集、削除を実行できないようにします。*

2021-02-20 15:48 UTC, fumi238000 commented
## 修正
- [ ]「未ログインユーザー」と「ログインユーザーがクリエイター」の場合、「 仕事を依頼するボタン」を非表示にする

2021-02-21 07:05 UTC, fumi238000 commented
## 変更点
- menuに関わる画面遷移の制限（before_action）
- ボタンの非表示（if文）
- menuのテストを実装（最低限）

## 補足
- テストコードのチェックよろしくお願いします。（不明点コメントしています。アドバイスいただけると幸いです。）

2021-02-22 12:46 UTC, great084 commented
確認しました。
以下の共通処理いいですね。他のControllerでも利用できると思います。

> application_controllerに判定用のメソッドを作成
> login_check ログインユーザーの判定
> clieter_check クライアントの判定
> creator_checkクリエイターの判定

Menuの更新（削除）に関しては上記の３つの判定に加えて、もう一つ制御が必要だと思います。
- メニューを作成したクリエイターが（menu.creator_id)、更新（削除）しようとしているユーザと一致しているかどうか
※現状、クリエイターであれば他の人が作成したメニューの更新（削除）が行えてしまうので、問題ありです。

2021-02-22 13:00 UTC, fumi238000 commented
ご確認頂きありがとうございます！

> 以下の共通処理いいですね。他のControllerでも利用できると思います。
>application_controllerに判定用のメソッドを作成
>login_check ログインユーザーの判定
>clieter_check クライアントの判定
>creator_checkクリエイターの判定
ありがとうございます！




>Menuの更新（削除）に関しては上記の３つの判定に加えて、もう一つ制御が必要だと思います。
>メニューを作成したクリエイターが（menu.creator_id)、更新（削除）しようとしているユーザと一致しているかどうか
>※現状、クリエイターであれば他の人が作成したメニューの更新（削除）が行えてしまうので、問題ありです。

その視点は抜けていました。
修正致します！

2021-02-22 13:38 UTC, great084 requested changes
修正してほしい点をコードに記載しています。
大きく以下３つの点を中心に記載していますので、修正願いいます。
・Menuの更新が自分のものかどうかの権限チェック
・user_idなど認証に必要な情報はviewから渡す情報を使用しないこと（controllerで取得する）
・ new, createメソッド時にはアソシエーションによって生成されてメソッド(ex. creator.menus.create(params))を使うと、設定が必要なパラメータも減ります。

2021-02-22 13:38 UTC, great084 commented on app/controllers/tasks_controller.rb
> +  before_action :creator_check, only: %i[create update edit]
create(仕事の依頼）はクリエイターではなく、クライアントですね。

2021-02-22 13:38 UTC, great084 commented on app/controllers/tasks_controller.rb
> +
上記に加えて、以下の制御が必要です。
仕事の参照：taskのcretor_id or client_id と一致するuserのみ
仕事（契約条件）の更新：taskのcreator_idと一致するuserのみ

2021-02-22 13:38 UTC, great084 commented on app/controllers/tasks_controller.rb
> +    end
creator_id, client_idをパラメータに入れると、書き換えることで他人の仕事を作成・操作、閲覧ができてしまいます。
ログインユーザを取得する必要があるものは、パラメータに入れず、controller側でcurrent_userから取得すべきです。

2021-02-22 13:38 UTC, great084 commented on app/models/task.rb
> +  enum status: { "契約前": 0, "支払い待ち": 1, "実施中": 2, "確認中": 3, "完了": 4 }
TBLには数字が入ります。number型で宣言していたので。modelのenumの宣言でstringに置き換えてくれます

2021-02-22 13:38 UTC, great084 commented on app/views/menus/_form.html.erb
> +<%= f.hidden_field :creator_id, value: current_user.id %>
このhidden項目は入れるべきではないです。（悪意を持った人が書き換えてpost 送信した際に、アカウント制御をすり抜けることになるので）
controller側で、current_userの情報を取得しましょう。

2021-02-22 13:38 UTC, great084 commented on app/views/menus/show.html.erb
> +                data: { confirm: '仕事を依頼します。よろしいでしょうか？'},
上記ボタンはクライアントが押すことになりますが、悪意を持った場合、contract_money、client_idなどパラメータを書き換える事が可能です。
ですので、最低限必要な情報(menu.id)のみを渡してあとはcontorller側でmenu情報、ユーザ情報を取得してください。

2021-02-22 13:38 UTC, great084 commented on app/controllers/tasks_controller.rb
> +    @task = Task.new(task_params)
アソシエーションで利用可能なメソッドを使って、
`current_user.tasks.build(task_params)`とするとcreator_idをparamsにセットする必要がなくなります。

2021-02-22 14:56 UTC, fumi238000 commented
## 修正
- [ ] Menuの更新が自分のものかどうかの権限チェック
- [ ] user_idなど認証に必要な情報はviewから渡す情報を使用しないこと（controllerで取得する）
- [ ] new, createメソッド時にはアソシエーションによって生成されてメソッド(ex. creator.menus.create(params))を使う

2021-02-24 14:47 UTC, great084 requested changes
処理内容概ね良いと思います。（細かい部分はソースにコメント入れています）
rspec実行してみたのですが、fail , errorがいくつかあるので、全てパスするようにしてほしいです。
(何らかの理由で現時点デカ確認できない場合は、pendingとしてください）

> enumは、現状の記述で問題ないでしょうか？
確認しました。現在の記載で良いです。（リファクタリングの余地はありますが、今後で良いです）

> ストロングパラメータへの記述のご確認よろしくお願いします。
確認しました。ソース内にコメント入れています。

>Task/createの記述チェックお願いします。
確認しました。OKです。（リファクタリングの余地はありますが、今後で良いです）

2021-02-24 14:47 UTC, great084 commented on app/controllers/menus_controller.rb
> +  before_action :creator_check,      only: %i[new create edit update destroy]
細かいですが、login_check, creator_checkの対象が同一で、かつcrator_checkの中で実質login_check文字実施しているので、login_checkは不要ではないでしょうか？

2021-02-24 14:47 UTC, great084 commented on app/controllers/tasks_controller.rb
> +    # TODO: 記述方法にチェックお願いいたします。
機能的にはOKだと思います。リファクタリングは後々で良いかと思います。

2021-02-24 14:47 UTC, great084 commented on app/models/task.rb
> +  enum status: { "契約前": 0, "支払い待ち": 1, "実施中": 2, "確認中": 3, "完了": 4 }
今の記述でOKですよ。あとはリファクタリングするとすれば、enumの文字列側の方を日本語ではなく、英語にして、別途日本語化の処理を入れる でしょうか。
※enumを英語設定したおくと、便利なメソッドが使えるため、
ex. enumの "契約前"を"before_contract"とすると、`Task.before_contract`で契約前の情報が抽出できたりします。

2021-02-24 14:47 UTC, great084 commented on spec/requests/menus_request_spec.rb
> +        expect { subject }.to change { Menu.count }.by(0)
```suggestion
        expect { subject }.to change { Menu.count }.by(1)
```
私が作成したときの誤りかもしれません。

2021-02-24 14:47 UTC, great084 commented on app/controllers/menus_controller.rb
> +      params.require(:menu).permit(:creator_id, :title, :price, :area, :thumbnail, :details).merge(creator_id: current_user.id)
後でcreater_idをマージするのでOKです。
view側creator_idをセットしなくなったので、permitの中から省いたほうが良いですね。

2021-02-24 15:53 UTC, fumi238000 commented on app/controllers/menus_controller.rb
> +  before_action :creator_check,      only: %i[new create edit update destroy]
おっしゃる通りです！削除しました！

2021-02-25 13:26 UTC, fumi238000 commented
## 修正
- [ ]  Menuリクエストスペックの実装
- [ ] Menuモデルスペックの実装（バリデージョン ）
- [ ] マイページの繋ぎ込み、削除
  - menus/index.html.erbに関わる部分を削除・調整
## 補足
- 今回のが落ち着きましたら、他のメンバーに迷惑がかからないうちにマージさせて頂きます。。

2021-02-26 12:35 UTC, great084 approved these changes
指摘内容修正されたことと、テストにerrorがないこと確認できました。
お疲れさまでした。

2021-02-26 13:33 UTC, yuukii125 approved these changes

2021-02-26 13:38 UTC, merged