【クライアント】決済機能を実装
great084/creator_match_pf pull request #68
Opened 2021-02-25 09:49 UTC by TAKO-zhangyu

## 実装の目的と概要
- クライアントの決済機能を実装

## 実装内容(技術的な点を記載)
- StripeのGemを導入
- 環境変数を用いてAPIキーを設定
- payments_controllerを作成
  - new, createアクションを作成
  
- newアクション
  - StripeのProduct・Priceを作成
  - 作成したProduct・Priceを元にCheckoutを用いて決済
  - 決済に成功したらcreateアクションへ移る

- createアクション
  - customer_idを格納（この処理のためにroutesにGETリクエストを設定している）

## 重点的に見てほしいところ(不安なところ)
 
 
## スクリーンショット（画面レイアウトを変更した場合）
### 画面名

## 参考資料
[【Stripeドキュメント】Productを作成](https://stripe.com/docs/api/products/create)
[【Stripeドキュメント】Priceを作成](https://stripe.com/docs/api/prices/create)
[【Qiita記事】Checkoutを用いて都度決済を実装](https://qiita.com/lumbermill/items/a05f8e9bf2160b0b84f1)

## チェックリスト

- [ ] ローカル環境での動作確認をしたか（影響し得る範囲も含めて）
- [ ] rubocopを実行して警告が出力されていないか
- [ ] GitHub で ファイル差分（Files changed）を確認し、内容が合っているか。不要なファイルに差分がでていないか

## 備考（実装していないことなど）
- 決済時に求められるメールアドレス入力を補完
- 決済完了後にマイページに遷移
- 決済キャンセル後に遷移するページの指定
- お仕事周り(tasksテーブル関連）のタスクが完了するまで行うことができない処理全て
  -  before_acrion
  - 決済を行う仕事の特定
  - StripeのProduct・Priceを作成する際に必要な商品名および契約金の情報受け取り
  - 決済完了時のtasksテーブルのstatusの変更

2021-02-26 10:56 UTC, great084 requested changes
いい感じですね！
ローカル環境で決済した内容が、すぐにStipeのダッシュボードで確認できて、使いやすいです。

一点、修正お願いしたい点あり。
クリマ側で同一ユーザが決済しても、Stripe側では別顧客として扱われて、決済の数だけ顧客が増えています。クリマとStripeでユーザが1:1になるようにしたいです。
Checkout時に前回取得した`stripe_customer_id`を設定すればいけるかと。

2021-02-26 10:56 UTC, great084 commented on app/controllers/payments_controller.rb
> +    @user = MemberInformation.where(user_id: current_user.id)
アソシエーションを利用して、以下の記述が良いですね。
`current_user.member_information`

2021-02-26 14:11 UTC, fumi238000 approved these changes

2021-03-01 06:28 UTC, great084 approved these changes
ありがとうございます。確認できました！

2021-03-01 22:55 UTC, merged